// Code generated by entc, DO NOT EDIT.

package vehicle

const (
	// Label holds the string label denoting the vehicle type in the database.
	Label = "vehicle"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldGarageID holds the string denoting the garage_id field in the database.
	FieldGarageID = "garage_id"
	// EdgeGarage holds the string denoting the garage edge name in mutations.
	EdgeGarage = "garage"
	// Table holds the table name of the vehicle in the database.
	Table = "vehicles"
	// GarageTable is the table that holds the garage relation/edge.
	GarageTable = "vehicles"
	// GarageInverseTable is the table name for the Garage entity.
	// It exists in this package in order to avoid circular dependency with the "garage" package.
	GarageInverseTable = "garages"
	// GarageColumn is the table column denoting the garage relation/edge.
	GarageColumn = "garage_id"
)

// Columns holds all SQL columns for vehicle fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldName,
	FieldGarageID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
