// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/bug/ent/garage"
	"entgo.io/bug/ent/plane"
	"entgo.io/ent/dialect/sql"
)

// Plane is the model entity for the Plane schema.
type Plane struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// GarageID holds the value of the "garage_id" field.
	GarageID *int `json:"garage_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlaneQuery when eager-loading is set.
	Edges PlaneEdges `json:"edges"`
}

// PlaneEdges holds the relations/edges for other nodes in the graph.
type PlaneEdges struct {
	// Garage holds the value of the garage edge.
	Garage *Garage `json:"garage,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// GarageOrErr returns the Garage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlaneEdges) GarageOrErr() (*Garage, error) {
	if e.loadedTypes[0] {
		if e.Garage == nil {
			// The edge garage was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: garage.Label}
		}
		return e.Garage, nil
	}
	return nil, &NotLoadedError{edge: "garage"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Plane) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case plane.FieldID, plane.FieldGarageID:
			values[i] = new(sql.NullInt64)
		case plane.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Plane", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Plane fields.
func (pl *Plane) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case plane.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pl.ID = int(value.Int64)
		case plane.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				pl.Name = value.String
			}
		case plane.FieldGarageID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field garage_id", values[i])
			} else if value.Valid {
				pl.GarageID = new(int)
				*pl.GarageID = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryGarage queries the "garage" edge of the Plane entity.
func (pl *Plane) QueryGarage() *GarageQuery {
	return (&PlaneClient{config: pl.config}).QueryGarage(pl)
}

// Update returns a builder for updating this Plane.
// Note that you need to call Plane.Unwrap() before calling this method if this Plane
// was returned from a transaction, and the transaction was committed or rolled back.
func (pl *Plane) Update() *PlaneUpdateOne {
	return (&PlaneClient{config: pl.config}).UpdateOne(pl)
}

// Unwrap unwraps the Plane entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pl *Plane) Unwrap() *Plane {
	tx, ok := pl.config.driver.(*txDriver)
	if !ok {
		panic("ent: Plane is not a transactional entity")
	}
	pl.config.driver = tx.drv
	return pl
}

// String implements the fmt.Stringer.
func (pl *Plane) String() string {
	var builder strings.Builder
	builder.WriteString("Plane(")
	builder.WriteString(fmt.Sprintf("id=%v", pl.ID))
	builder.WriteString(", name=")
	builder.WriteString(pl.Name)
	if v := pl.GarageID; v != nil {
		builder.WriteString(", garage_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Planes is a parsable slice of Plane.
type Planes []*Plane

func (pl Planes) config(cfg config) {
	for _i := range pl {
		pl[_i].config = cfg
	}
}
